#!/usr/bin/env bash
#!/usr/bin/env bash
# login to server
#!/usr/bin/env bash
# login to server
# Setting up the ssh-agent
eval $("ssh-agent")
# Path to IdentityFile
ssh-add ~/root/.ssh/school
# Username and IP Address
ssh ubuntu@54.146.77.72
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"web-02" 11L, 188C                                 11,23         All
